### ISSUE TITLE
[BUG] Server crashing with new version v1.1.0

### ISSUE THREAD

**Issue by csportalsk** [abnerfs/cs2-rockthevote#15]
CSSv 159, Metamod:Source version 2.0.0-dev+1229, +game_type 0 +game_mode 0, roundtime 35, surf server
```
[EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at cs2_rockthevote.GameRules.SetGameRules() in C:\Users\Abner\source\repos\cs2-rockthevote\RockTheVote\CrossCutting\GameRules.cs:line 29
   at cs2_rockthevote.Plugin.OnRoundStartGameRules(EventRoundStart event, GameEventInfo info) in C:\Users\Abner\source\repos\cs2-rockthevote\RockTheVote\CrossCutting\GameRules.cs:line 13
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```

**Comment by abnerfs** [comment]
I've recompiled the plugin with the latest CS# version v162 can you update CS# and try the latest version? https://github.com/abnerfs/cs2-rockthevote/releases
