### ISSUE TITLE
Issue while the server starts

### ISSUE THREAD

**Issue by newkid3000** [abnerfs/cs2-rockthevote#22]
I'm getting the following error while a server start:

`[EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at cs2_rockthevote.GameRules.get_WarmupRunning() in /home/runner/work/cs2-rockthevote/cs2-rockthevote/CrossCutting/GameRules.cs:line 50
   at cs2_rockthevote.EndOfMapVote.<>c__DisplayClass13_0.<OnLoad>b__0(EventRoundStart ev, GameEventInfo info) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Features/EndOfMapVote.cs:line 62
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---`

**Comment by abnerfs** [comment]
Hey I believe it's because you have an outdated config, can you delete your existing config and let the plugin recreate it?
