### ISSUE TITLE
Latest version 1.8.1 shows error when starting the server

### ISSUE THREAD

**Issue by BoTo-sg** [abnerfs/cs2-rockthevote#43]
23:15:04 [INFO] (cssharp:PluginContext) Loading plugin RockTheVote
23:15:04 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/RockTheVote/RockTheVote.dll
System.NullReferenceException: Object reference not set to an instance of an object.
   at cs2_rockthevote.Core.MapCooldown.<.ctor>b__5_0(Object e, Map[] maps) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Core/MapCooldown.cs:line 24
   at cs2_rockthevote.MapLister.LoadMaps() in /home/runner/work/cs2-rockthevote/cs2-rockthevote/CrossCutting/MapLister.cs:line 46
   at cs2_rockthevote.MapLister.OnLoad(Plugin plugin) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/CrossCutting/MapLister.cs:line 59
   at cs2_rockthevote.DependencyManager`2.OnPluginLoad(TPlugin plugin) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/CrossCutting/DependencyManager.cs:line 51
   at cs2_rockthevote.Plugin.Load(Boolean hotReload) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Plugin.cs:line 62
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

**Comment by criskkky** [comment]
Same here

**Comment by abnerfs** [comment]
Fix should fix the issue: https://github.com/abnerfs/cs2-rockthevote/releases/tag/v1.8.2
