### ISSUE TITLE
 rtv Error 

### ISSUE THREAD

**Issue by maketou** [abnerfs/cs2-rockthevote#44]
When type rtv

06:22:02 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot transcode invalid UTF-8 JSON text to UTF-16 string.
 ---> System.Text.DecoderFallbackException: Unable to translate bytes [D3] at index 6 from specified code page to Unicode.
   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
   at System.Text.Encoding.GetCharCountWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, DecoderNLS decoder)
   at System.Text.Encoding.GetCharCountWithFallback(Byte* pBytesOriginal, Int32 originalByteCount, Int32 bytesConsumedSoFar)
   at System.Text.UTF8Encoding.GetCharCount(Byte* bytes, Int32 count)
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.Encoding.GetString(ReadOnlySpan`1 bytes)
   at System.Text.Json.JsonReaderHelper.TranscodeHelper(ReadOnlySpan`1 utf8Unescaped)
   --- End of inner exception stack trace ---
   at System.Text.Json.JsonReaderHelper.TranscodeHelper(ReadOnlySpan`1 utf8Unescaped)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.<>c.<LoadJsonResources>b__13_1(JsonProperty e) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 147
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.LoadJsonResources(String filePath) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 147
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.TryLoadResourceSet(String cultureName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 124
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.TryLoadResourceSet(CultureInfo culture) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 135
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.GetResourceSet(CultureInfo culture, Boolean tryParents) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 36
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.GetString(String name, CultureInfo culture) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 108
   at CounterStrikeSharp.API.Core.Translations.JsonStringLocalizer.GetStringSafely(String name, CultureInfo culture) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonStringLocalizer.cs:line 65
   at CounterStrikeSharp.API.Core.Translations.JsonStringLocalizer.get_Item(String name) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonStringLocalizer.cs:line 34
   at CounterStrikeSharp.API.Core.Translations.StringLocalizer.get_Item(String name) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/StringLocalizer.cs:line 18
   at cs2_rockthevote.StringLocalizer.LocalizeWithPrefixInternal(String prefix, String key, Object[] args) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/CrossCutting/StringLocalizer.cs:line 30
   at cs2_rockthevote.StringLocalizer.LocalizeWithPrefix(String key, Object[] args) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/CrossCutting/StringLocalizer.cs:line 35
   at cs2_rockthevote.RockTheVoteCommand.CommandHandler(CCSPlayerController player) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Features/RockTheVoteCommand.cs:line 93
   at cs2_rockthevote.Plugin.OnChat(EventPlayerChat event, GameEventInfo info) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Plugin.cs:line 75
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120

**Comment by maketou** [comment]
//Put your map list here
de_thera:3121217565
de_cache:3070596702
de_favela_d_prefab:3071414315
de_season_d_prefab:3073892687
de_vertigo
de_inferno
de_mirage
de_ancient
de_nuke
de_anubis
de_overpass
de_dust2

**Comment by maketou** [comment]
css
  CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.
  Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison, source2gen and CS2Fixes.
  See ACKNOWLEDGEMENTS.md for more information.
  Current API Version: 195

**Comment by maketou** [comment]
Ftp Edit code error
Re-upload the original file and fix the error

**Comment by maketou** [comment]
Ftp Edit code error
Re-upload the original file and fix the error
