### ISSUE TITLE
[BUG] Error invoking callback | Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by crashzk** [abnerfs/cs2-rockthevote#53]
The end-of-map vote ends, but the map does not change to the map that won the vote.

Simply switch to the same map you are running on.

Log error:
```
2024-03-28 23:51:09.293 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at cs2_rockthevote.ChangeMapManager.<ChangeNextMap>b__17_0() in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Core/ChangeMapManager.cs:line 81
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

Plugin Version: 2.0.0
CSSharp Version: 202 (1.0.202+696ecad)

Map list:
```
de_mirage
de_vertigo
de_inferno
de_anubis
de_dust2
de_ancient
de_nuke
de_overpass
```

[RockTheVote.json](https://github.com/abnerfs/cs2-rockthevote/files/14805213/RockTheVote.json)

**Comment by crashzk** [comment]
@abnerfs fix?
