### ISSUE TITLE
The !nominate menu no longer works after CS2 update. You can nominate a specific map using !nominate (map), but the menu isn't working.

### ISSUE THREAD

**Issue by alnoisegit** [abnerfs/cs2-rockthevote#54]
This is the console log when doing !nominate

```
09:20:48 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CounterStrikeSharp.API.Modules.Menu.ChatMenuInstance.Display() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/ChatMenu.cs:line 42
   at CounterStrikeSharp.API.Modules.Menu.MenuManager.OpenChatMenu(CCSPlayerController player, ChatMenu menu) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/MenuManager.cs:line 50
   at cs2_rockthevote.NominationCommand.OpenNominationMenu(CCSPlayerController player) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Features/NominationCommand.cs:line 117
   at cs2_rockthevote.NominationCommand.CommandHandler(CCSPlayerController player, String map) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Features/NominationCommand.cs:line 107
   at cs2_rockthevote.Plugin.OnNominate(CCSPlayerController player, CommandInfo command) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Features/NominationCommand.cs:line 17
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 159
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context)
```

**Comment by alnoisegit** [comment]
This only happens with 0 maps in cooldown. When I changed that back to 3 the nominate menu started working again.
